// Mark Dolan Info Functions
// link_string - brings in links accordion and footer

var link_string =  [
		'<h3>Other Links</h3><div class="row">',
				"<div class=\"panel-group\" id=\"accordion\">",
						"<div class=\"panel panel-default\">",
								"<div class=\"panel-heading\">",
										"<h4 class=\"panel-title\">",
												"<a href=\"#social\" class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion\">",
												"<span class=\"glyphicon glyphicon-user\"></span> Social Media</a>",
										"</h4>",
										"</div>",
								"<div id=\"social\" class=\"panel-collapse collapse\">",
										"<div class=\"panel-body\">",
												"<ul>",
												"<li><a href=\"https://www.facebook.com/profile.php?id=100005819415030\">Facebook</a></li>",
												"<li><a href=\"https://plus.google.com/u/0/114610811783469908369/posts\">Google+</a></li>",
												"<li><a href=\"https://twitter.com/markdolan1024\">Follow @markdolan1024</a></li>",
												"<li><a href=\"https://github.com/MarkElmerDolan\">Git Repos</a></li>",
												"<li><a href=\"http://markelmerdolan.blogspot.com/\">Mark Elmer Dolan Blog</a></li>",
												"<li><a href=\"http://prezi.com/user/m5skbzgibuga\">My Prezi Account</a></li>",
												"<li><a href=\"https://www.youtube.com/channel/UCwJP-4gL8BV5_JTR7KaqECw\">YOUTUBE Account</a></li>",
												"<li><a href=\"https://markelmerdolan.wordpress.com\">My Wordpress Blog</a></li>",
												"</ul>",
										"</div>",
								"</div>",
								"<div class=\"panel-heading\">",
										"<h4 class=\"panel-title\">",
										"<a href=\"#working\" class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion\">",
										"<span class=\"glyphicon glyphicon-ok-circle\"></span> Working Sites</a>",
										"</h4>",
								"</div>",
								"<div id=\"working\" class=\"panel-collapse collapse\">",
										"<div class=\"panel-body\">",
												"<ul>",
												"<li><a href=\"http://cis-linux2.temple.edu/~tue79412/sciencetap/www/weather.html\">Sciencetap Project</a></li>",
												"<li><a href=\"http://astro.temple.edu/~tue79412/index.html\">Temple Astro Site</a></li>",
												"<li><a href=\"http://cis-linux2.temple.edu/~tue79412/index.php\">My Web Apps</a></li>",
												"</ul>",
										"</div>",
								"</div>",
								"<div class=\"panel-heading\">",
										"<h4 class=\"panel-title\">",
										"<a href=\"#google\" class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#accordion\">",
										"<span class=\"glyphicon glyphicon-pushpin\"></span> Google Sites</a>",
										"</h4>",
								"</div>",
								"<div id=\"google\" class=\"panel-collapse collapse\">",
										"<div class=\"panel-body\">",
												"<ul>",
												"<li><a href=\"https://sites.google.com/site/dolanmarkpa/\">Temple University Classwork</a></li>",
												"<li><a href=\"https://sites.google.com/site/markdolanelmer/\">GMail Site Projects</a></li>",
												"<li><a href=\"https://sites.google.com/site/markelmerdolan/\">GMail Site Artwork</a></li>",
												"<li><a href=\"https://sites.google.com/site/markelmerdolanphiladelphia/\">GMail Working Site</a></li>",
												"<li><a href=\"https://sites.google.com/site/markelmerdolanprogramming/\">Mark Elmer Dolan Programming</a></li>",
												"<li><a href=\"https://sites.google.com/site/markdolanphiladelphia/\">Mark Elmer Dolan Philadelphia Art</a>                 </li>",
												"<li><a href=\"https://sites.google.com/site/markelmerdolancis/\">Mark Elmer Dolan CIS</a></li>",
												"<li><a href=\"https://sites.google.com/site/markelmerdolanphysics/\">Mark Elmer Dolan Physics</a></li>",
												"<li><a href=\"https://sites.google.com/site/markelmerdolanphillyart/\">Mark Elmer Dolan Artwork</a></li>",
												"<li><a href=\"https://sites.google.com/site/markelmerdolanprojects/\">Mark Elmer Dolan Projects</a> </li>",
												"</ul>",
										"</div>",
								"</div>",
						"</div>",
				'</div></div>',
				'<footer id="contact_info" class="row">',
						"<p> ",
						"Contact Info:<br>",
						"Mark Elmer Dolan<br>",
						"Ardmore, PA<br>",
						"markdolan1024 AT gmail.com<br>",
						"</p>",
						"<a href=\"https://twitter.com/markdolan1024\" class=\"twitter-follow-button\" data-show-count=\"false\">Follow @markdolan1024</a>",
						"<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>",
				"</footer>"
];

var nav_string =  [
		"<div class=\"row\">",
				"<nav class=\"navbar navbar-default navbar-fixed-top navbar-inverse\">",
						"<div class=\"navbar-header\">",
								"<button type\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#collapse\">",
										"<span class=\"sr-only\">Toggle Navigation</span>",
										"<span class=\"icon-bar\"></span>",
										"<span class=\"icon-bar\"></span>",
										"<span class=\"icon-bar\"></span>",
								"</button>",
						"</div>",
						"<div class=\"collapse navbar-collapse\" id=\"collapse\">",
								'<ul id="menu_links" class="nav navbar-nav">',
								"<li><a href=\"index.html\">Home</a></li>",
								'<li><a href="tutorials.html">Tutorials</a></li>',
								'<li><a href="examples.html">Examples</a></li>',
								"</ul>",
						"</div>",
				"</nav>",
		"</div>"
];
